# Generated by Django 4.2 on 2024-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_managerapp', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='spending',
            field=models.FloatField(default=0),
        ),
    ]
